### ISSUE TITLE
ABP_Rampage.uasset & T-Pose.uasset can't open in UE4

### ISSUE THREAD

**Issue by avoien** [MeleeCampz/IMU-Based-Motion-Capturing#1]
I use UE 4.19.2 and I load this project success.

But I can't open ABP_Rampage.uasset and T-Pose.uasset in UE4 .

can you update these two files ?

Thank you very much,.

**Comment by MeleeCampz** [comment]
@avoien As the Paragon Rampage Character Assets where to large for a free github repository (>5GB), i removed it completely from the project and replaced all references. Everything should import work properly now. Please tell me if you have further problems
