### ISSUE TITLE
Crash on Play start with MainMenu

### ISSUE THREAD

**Issue by avoien** [MeleeCampz/IMU-Based-Motion-Capturing#2]
Since I Play in Editor from MainMenu, and Choice Character Button,
The Exception was happened

Play in editor start time for /Game/UEDPIE_0_MainMenu -0.229
TravelFailure: InvalidURL, Reason for Failure: 'Invalid URL: /Game/MainMenu'. Shutting down PIE.
TravelFailure: ClientTravelFailure, Reason for Failure: 'Invalid URL: /Game/MainMenu'. Shutting down PIE.

have any idea ?

**Comment by MeleeCampz** [comment]
I found the error. when cleaning up the repository I renamed a map file; I fixed the blueprint on the "Character" button and it should work again now
